language:
  ruby

rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - 2.6.0
  - 2.7.0
  - 3.0.0

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgsl0-dev
  - gem install bundler:1.17.3
  - bundle _1.17.3_ install
  - bundle exec rake compile
  - bundle exec rake test
